# The version of the docker-compose.
version: "3.8"
services:
  client:
    build: ./client
    container_name: chat-client
    ports:
      - "3000:3000"

  server:
    build: ./server
    container_name: chat-server
    ports:
      - "5000:5000"